version: '3.8'

services:
  mysqldb:
    image: 'mysql:lts'
    container_name: "mysqldb"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=authdb
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 5
      start_period: 10s
    ports:
      - "3333:3306" 
    volumes:
      - ./installation_help/mysqldemo.sql:/docker-entrypoint-initdb.d/mysqldemo.sql  # Mount the SQL file here
    networks:
      - mynetwork

  redisdb:
    image: 'redis:latest'
    container_name: 'redisdb'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  iam:
    build: ./  # Builds the image from the Dockerfile in the current directory
    image: 'iam:01'
    container_name: 'iam'
    depends_on:
      mysqldb:
        condition: service_healthy
      redisdb:
        condition: service_healthy  # Ensure Redis is healthy before starting 'iam'
    environment:
      - MYSQL_HOST=mysqldb
      - REDIS_HOST=redisdb
      - IAM_SERVICE_URL=http://localhost:8000/
    ports:
      - "8000:8000"  # Expose necessary ports if applicable
    networks:
      - mynetwork  # Ensure all services are on the same network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/auth/v1/health_check"]  # Example health check if you have a /health endpoint
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  mynetwork:
    driver: bridge
